#!/bin/bash
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
export RAILS_ENV=production
export DB=postgres
cd /opt/home/diaspora/diaspora
exec bundle exec passenger start --max-pool-size=4 --min-instances=4 --pool-idle-time=120
